spring:
  jpa:
    open-in-view: 'false'
    database-platform: org.hibernate.dialect.MySQL57Dialect
    defer-datasource-initialization: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1;
  h2:
    console:
      enabled: 'true'
      path: /h2-console
  profiles:
    default: default