server:
  port: 8080
  servlet:
    session:
      timeout: 8760h
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  config:
    import:
      application-oauth.yml

  jpa:
    open-in-view: 'false'
    database-platform: org.hibernate.dialect.MySQL57Dialect
    defer-datasource-initialization: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update # create or update

  datasource:
    username: bo
    url: jdbc:h2:mem:bhDB;MODE=MYSQL;DB_CLOSE_DELAY=-1;

  h2:
    console:
      enabled: 'true'
      path: /h2-console

  profiles:
    default: default