server:
  port: 8080
  servlet:
    session:
      timeout: 2592000 # 24시간 ( 1년 : 525600m )
      cookie:
        max-age: 2592000 # 48시간 ( 1년 : 525600m )
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  profiles:
    default: local