server:
  port: 8080
  servlet:
    session:
      timeout: 525600m # 1년
      cookie:
        max-age: 525600m # 1년
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  profiles:
    default: local