server:
  port: 8080
  servlet:
    session:
      timeout: 2592000 # 24시간 ( 1년 : 525600m )
      cookie:
        max-age: 2592000 # 48시간 ( 1년 : 525600m )
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  profiles:
    default: dev

cloud:
  aws:
    credentials:
      access-key: AKIAWPNQAP77SDWADWV2
      secret-key: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: dev-s3-beforehairshop

cloud.aws.sqs.response-queue.name: dev-inference-response-queue
cloud.aws.sqs.request-queue.name: dev-inference-request-queue


cloud.aws.cloudfront.domain: https://d2fbb7tycgdtir.cloudfront.net